name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn build
        working-directory: frontend
